#!/bin/bash
echo "========================================="
echo "  Démarrage Service Python COFIBANK"
echo "========================================="
echo ""
echo "ATTENTION: Vous devez d'abord installer les prérequis :"
echo "  sudo apt install python3-venv python3-pip"
echo ""
echo "Puis exécutez :"
echo "  cd python-service"
echo "  python3 -m venv venv"
echo "  source venv/bin/activate"
echo "  pip install -r requirements.txt"
echo "  uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
echo ""
echo "Ou utilisez le script installer-et-demarrer.sh"
echo ""
